"use client";

import { useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function DownloadExpenses() {
  const [loading, setLoading] = useState(false);

  const handleDownload = async () => {
    try {
      setLoading(true);

      const savedUser =
        localStorage.getItem("spendwiseUser");

      if (!savedUser) {
        alert("Please login again.");
        return;
      }

      const user = JSON.parse(savedUser);

      const response = await fetch(
        `${process.env.NEXT_PUBLIC_API_URL}/api/expenses/${user.id}`
      );

      const data = await response.json();

      if (!response.ok) {
        alert(
          data.message ||
            "Failed to download expenses."
        );
        return;
      }

      const expenses = data.expenses || [];

      if (expenses.length === 0) {
        alert(
          "You don't have any expenses to download."
        );
        return;
      }

      const doc = new jsPDF();

      /* Header */

      doc.setFontSize(22);
      doc.setTextColor(24, 59, 42);
      doc.text("SpendWise", 14, 20);

      doc.setFontSize(14);
      doc.setTextColor(82, 97, 88);
      doc.text("Expense Report", 14, 29);

      doc.setFontSize(10);
      doc.setTextColor(120, 130, 124);
      doc.text(
        `Generated for ${user.name}`,
        14,
        37
      );

      /* Expense Table */

      const tableRows = expenses.map(
        (expense: {
          expense_date: string;
          category: string;
          description: string | null;
          amount: string | number;
        }) => [
          expense.expense_date.split("T")[0],
          expense.category,
          expense.description || "-",
          `Rs. ${Number(expense.amount).toFixed(2)}`,
        ]
      );

      autoTable(doc, {
        startY: 45,
        head: [
          [
            "Date",
            "Category",
            "Description",
            "Amount",
          ],
        ],
        body: tableRows,

        theme: "grid",

        headStyles: {
          fillColor: [24, 59, 42],
          textColor: [255, 255, 255],
          fontStyle: "bold",
        },

        styles: {
          fontSize: 9,
          cellPadding: 4,
        },

        columnStyles: {
          0: {
            cellWidth: 30,
          },
          1: {
            cellWidth: 35,
          },
          2: {
            cellWidth: 85,
          },
          3: {
            cellWidth: 35,
            halign: "right",
          },
        },
      });

      /* Total */

      const total = expenses.reduce(
        (
          sum: number,
          expense: {
            amount: string | number;
          }
        ) =>
          sum + Number(expense.amount),
        0
      );

      const finalY =
        (doc as any).lastAutoTable.finalY + 12;

      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(24, 59, 42);

      doc.text(
        `Total Expenses: Rs. ${total.toFixed(2)}`,
        14,
        finalY
      );

      /* Footer */

      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(140, 145, 142);

      doc.text(
        "Generated by SpendWise",
        14,
        285
      );

      doc.save("spendwise-expense-report.pdf");
    } catch (error) {
      console.error(
        "Download expenses error:",
        error
      );

      alert(
        "Unable to download expense report."
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <button
      type="button"
      onClick={handleDownload}
      disabled={loading}
      className="cursor-pointer rounded-xl border border-[#CBD5CC] bg-white px-4 py-2.5 text-sm font-semibold text-[#183B2A] transition hover:bg-[#F0F3ED] disabled:cursor-not-allowed disabled:opacity-60"
    >
      {loading
        ? "Preparing..."
        : "↓ Download Report"}
    </button>
  );
}